# Generated by Django 5.0.3 on 2024-04-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_deadline_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
