# Generated by Django 5.0.3 on 2024-04-04 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_deadline_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 16, 11, 3, 221954, tzinfo=datetime.timezone.utc)),
        ),
    ]
