# Generated by Django 5.0.3 on 2024-04-04 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 16, 21, 27, 299264, tzinfo=datetime.timezone.utc)),
        ),
    ]
