# Generated by Django 5.0.3 on 2024-04-05 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_task_done_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 3, 14, 4, 191336, tzinfo=datetime.timezone.utc)),
        ),
    ]
