# Generated by Django 5.0.3 on 2024-04-06 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 13, 39, 27, 914902, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='deadline',
        ),
    ]
